JAVA_OPTS=-Xmx1536m -Xms512m -XX:MaxDirectMemorySize=128m -XX:MaxMetaspaceSize=192m -XX:ReservedCodeCacheSize=64m
JAVA_OPTS_FOR_JDK_17=-Xmx1536m -Xms512m -XX:MaxDirectMemorySize=128m -XX:MaxMetaspaceSize=192m -XX:ReservedCodeCacheSize=64m
priority_networks = 172.20.80.0/24
